Identify the list of allowed required constraints for getUserMedia
w3c/mediacapture-main pull request #707
Opened 2020-07-23 10:26 UTC by youennf

In case an unallowed required constraint is given to getUserMedia, skip it.
This would help https://github.com/w3c/mediacapture-image/issues/229.

2020-08-21 06:21 UTC, beaufortfrancois commented
@jan-ivar @alvestrand  What are your thoughts?

2020-09-17 14:23 UTC, henbos approved these changes

2020-09-17 14:24 UTC, henbos commented on getusermedia.html
> +                        and whose name is not in <a>getUserMedia allowed required constraint list</a>.</li>
Should we throw OverconstrainedError?

2020-09-17 14:29 UTC, alvestrand commented on getusermedia.html
> +        <p>The <dfn>getUserMedia allowed required constraint list</dfn>
Suggest renaming this to "allowed required constraints for device selection", to make it more obvious that applyConstraints() is still allowed to use required constraints for other names.

2020-09-17 14:29 UTC, henbos commented
Editors can integrate with comments addressed

2020-09-24 13:38 UTC, youennf commented on getusermedia.html
> +                        and whose name is not in <a>getUserMedia allowed required constraint list</a>.</li>
Updated accordingly

2020-09-24 13:39 UTC, youennf commented on getusermedia.html
> +        <p>The <dfn>getUserMedia allowed required constraint list</dfn>
Updated accordingly

2020-09-24 17:12 UTC, dontcallmedom commented on getusermedia.html
> +                        that is <a data-lt="required">required</a> and whose name is not in the
data-lt not needed
```suggestion
                        that is <a>required</a> and whose name is not in the
```

2020-09-24 21:49 UTC, jan-ivar requested changes

2020-09-24 21:49 UTC, jan-ivar commented on getusermedia.html
> +                        jump to the step labeled <em>Constraint Failure</em> below.</p></li>
We have a [precedent](https://github.com/w3c/mediacapture-image/pull/261#issuecomment-698514049) in screen-capture we can copy for navigating these dictionaries.

Also, for consistency, we think in https://github.com/w3c/mediacapture-image/pull/261#issuecomment-698516937 it should throw `TypeError`.

```suggestion
                        <li><p>If <var>CS</var> contains a member whose name is not in the
                        list of <a>allowed required constraints for device selection</a>,
                        and whose value in turn is a dictionary containing a member named
                        <code>min</code>, <code>max</code>, or <code>exact</code>,
                        then <a>reject</a> <var>p</var> with a {{TypeError}}, and abort
                        these steps.</p></li>
```

2020-09-24 22:02 UTC, jan-ivar commented on getusermedia.html
> +        </p>
This change flips the default behavior on all other constraints, e.g. all [image capture constraints](https://w3c.github.io/mediacapture-image/#mediatrackconstraintset-section):
```js
  ConstrainDOMString           whiteBalanceMode;
  ConstrainDOMString           exposureMode;
  ConstrainDOMString           focusMode;
  ConstrainPoint2D             pointsOfInterest;

  ConstrainDouble              exposureCompensation;
  ConstrainDouble              exposureTime;
  ConstrainDouble              colorTemperature;
  ConstrainDouble              iso;

  ConstrainDouble              brightness;
  ConstrainDouble              contrast;
  ConstrainDouble              saturation;
  ConstrainDouble              sharpness;

  ConstrainDouble              focusDistance;
  (boolean or ConstrainDouble) pan;
  (boolean or ConstrainDouble) tilt;
  (boolean or ConstrainDouble) zoom;

  ConstrainBoolean             torch;
```
@youennf Was that the intent? Or does imageCapture need a PR as well?

Did we consider having a deny list instead with just pan, tilt and zoom?

2020-09-28 09:58 UTC, youennf commented on getusermedia.html
> +        </p>
That is the intent. mediacapture-image will have to do dedicated opt-in.
A deny list is not great since we want to move to a world where required constraints disappear from getUserMedia.
For that reason, I would hope we could agree in not adding any additional required constraints to this list.

2020-09-28 10:02 UTC, youennf commented on getusermedia.html
> +                        jump to the step labeled <em>Constraint Failure</em> below.</p></li>
> We have a [precedent](https://github.com/w3c/mediacapture-image/pull/261#issuecomment-698514049) in screen-capture we can copy for navigating these dictionaries.

What is the benefit? I prefer referring to a concept (required, defined in https://w3c.github.io/mediacapture-main/#dfn-required-constraints) instead of trying to inline the definition of the concept. I would tend to fix media capture-screenshare so that it refers to the concept in mediacapture-main.

Or do you want to disallow these constraints in advanced constraints too?

I am ok with TypeError instead of OverConstrained.

2020-09-29 01:41 UTC, jan-ivar commented on getusermedia.html
> +                        jump to the step labeled <em>Constraint Failure</em> below.</p></li>
@youennf All inputs can be validated using the terminology of the incoming data type. No need to involve concepts.

The input we're reading here is a dictionary, which does not contain a "constrainable property" (which is even the wrong concept, it should at least be "constraint") but a [member](https://heycam.github.io/webidl/#dfn-dictionary-member), which has a name (aka key) and a value.

The problem I have using our concepts is that they're complicated and harder to navigate than the WebIDL primitives.

For example, "constrainable property" != "constraint". "[required](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-required)" != "[required constraint](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-required-constraints)".

Specifically, I worry that the sentence _"If CS contains a constrainable property that is **required**"_ is vague about whether to reject on `advanced` constraints which are also [required](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-required) and also something the CS may "contain".

I also worry implementers may miss that the dictionary to inspect is nested one level down.

2020-09-29 06:24 UTC, youennf commented on getusermedia.html
> +                        jump to the step labeled <em>Constraint Failure</em> below.</p></li>
> I worry that the sentence _"If CS contains a constrainable property that is **required**"_ is vague about whether to reject on `advanced` constraints which are also [required](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-required) and also something the CS may "contain".

That is why the term "required" is a link that points to the following definition:
"required constraints are all non-advanced constraints that are required."

We could rephrase a bit the sentence though to use the term "required constraint".
This term is already used in getUserMedia just below. I do not think implementors will miss the difference here.

I think this PR is clear about allowing advanced constraints that are required.
We might want to further restrict this but this could be done as a follow-up.

2020-09-29 13:57 UTC, jan-ivar commented on getusermedia.html
> +                        jump to the step labeled <em>Constraint Failure</em> below.</p></li>
> That is why the term "required" is a link that points to the following definition:
"required constraints are all non-advanced constraints that are [required](https://w3c.github.io/mediacapture-main/#dfn-required)."

@youennf but that's not where it links. You're using `<a>required</a>` which links to the [required](https://w3c.github.io/mediacapture-main/#dfn-required) definition which doesn't preclude `advanced` constraints. This is the kind of confusion I'm talking about.

 Also the terminology is wrong. How about:
```suggestion
                        <li><p>If <var>CS</var> contains a member that is a
                        <a>required constraint</a> and whose name is not in the
                        list of <a>allowed required constraints for device selection</a>,
                        then <a>reject</a> <var>p</var> with a {{TypeError}}, and abort
                        these steps.</p></li>
```

2020-09-29 14:03 UTC, youennf commented on getusermedia.html
> +                        jump to the step labeled <em>Constraint Failure</em> below.</p></li>
I see, thxs for the update.

2020-09-29 14:03 UTC, youennf commented
Are we good margin the PR?

2020-09-29 14:07 UTC, jan-ivar approved these changes

2020-09-29 14:09 UTC, merged