Define the fitness distance for unexposed constraints
w3c/mediacapture-main pull request #742
Opened 2020-10-30 16:06 UTC by eehakkin

This is to clarify meaning of presence of certain constraints (especially PTZ constraints) when devices do not support them, as discussed in TPAC meeting.

This also partially addresses https://github.com/w3c/mediacapture-image/issues/256.

2020-11-02 09:54 UTC, guidou approved these changes
I think we need additional language to cover the special true/{} case for PTS, but I guess that should be covered in the image capture spec.

2020-11-05 15:00 UTC, jan-ivar requested changes

2020-11-05 15:00 UTC, jan-ivar commented on getusermedia.html
> +                  distance is 1.</p>
I think this is the right place, but I'm not sure those are the ingredients. I think we need something like this:

_"If the constraint is [not required](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-required), applies for this type of device but not this particular device, and the constrainable property is not on the [list of inherent constrainable track properties](https://w3c.github.io/mediacapture-main/getusermedia.html#list-of-inherent-constrainable-track-properties), then the fitness distance is 1 (that is, the presence of a constraint does not influence the fitness distance)."_

2020-11-09 21:13 UTC, eehakkin commented on getusermedia.html
> +                  distance is 1.</p>
That might be in the right direction, but I  think that it is not enough.

I think that the condition **_the constraint is [not required](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-required)_** is extraneous. That leaves the fitness distance undefined when a constrain is required, the settings dictionary somehow satisfies the constraint and an ideal value is specified but does not apply for this particular device.
Something like `{foo: {exact: false, ideal: "bar"}}` and a settings dictionary for a foo incapable device. In that case the fitness distance should probably be 1 so this step should define the fitness distance. Also, there is no _actual_ foo value to compare against so the remaining steps cannot define the fitness distance.

The condition **_[the constraint] applies for this type of device_** is probably not strictly needed (because the  [fitness distance](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-fitness-distance) step 3 already defines the fitness distance to be 0 if the constraint does not apply for this type of device) but it does no harm.

I think that the condition **_[the constraint does] not [apply for] this particular device_** is problematic. If a constraint set is `{zoom: {ideal: 2}}` and the device is zoom capable (thus the constraint applies for this particular device) but the UA does not expose the setting (due to permissions for instance and thus the settings dictionary does not have a setting for the zoom), shouldn't the fitness distance still be 1? Otherwise the application could select devices based on unexposed constrainable properties.

2021-01-13 15:22 UTC, jan-ivar commented on getusermedia.html
> +                  distance is 1.</p>
> I think that the condition **_the constraint is [not required](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-required)_** is extraneous. That leaves the fitness distance undefined when a constrain is required,

By definition, satisfied required constraints don't have fitness distance. They're delimiters (`min` or `max`) or hard requirements (`exact`), whose sole purpose is candidate elimination.

> the settings dictionary somehow satisfies the constraint and an ideal value is specified but does not apply for this particular device.
> Something like `{foo: {exact: false, ideal: "bar"}}` and a settings dictionary for a foo incapable device. In that case the fitness distance should probably be 1

I think it needs to be `Infinity`, by the same logic that they're unfit, from https://github.com/w3c/mediacapture-image/issues/256

E.g. had we still supported required constraints for `pan`, we'd agree non-ptz cameras shouldn't satisfy
```js
await navigator.mediaDevices.getUserMedia({video: {pan: {exact: 0}}}); // OverconstrainedError
```
Now `pan` is not on the list of [allowed required constraints for device selection](https://w3c.github.io/mediacapture-main/#dfn-allowed-required-constraints-for-device-selection) so it throws `TypeError` before we get this far. But for other future constraints, I think `Infinity` would be correct.

> The condition **_[the constraint] applies for this type of device_** is probably not strictly needed (because the [fitness distance](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-fitness-distance) step 3 already defines the fitness distance to be 0 if the constraint does not apply for this type of device) but it does no harm.

Yeah unfortunately, the reliance on order here is not terribly explicit, so being overly specific might be necessary.

> I think that the condition **_[the constraint does] not [apply for] this particular device_** is problematic. If a constraint set is `{zoom: {ideal: 2}}` and the device is zoom capable (thus the constraint applies for this particular device) but the UA does not expose the setting (due to permissions for instance and thus the settings dictionary does not have a setting for the zoom), shouldn't the fitness distance still be 1? Otherwise the application could select devices based on unexposed constrainable properties.

This seems like an existing problem imageCapture needs to handle. How does it avoid device selection by ptz today?

2021-01-14 15:22 UTC, jan-ivar commented on getusermedia.html
> +                  distance is 1.</p>
I also propose the following further up:
```
               <p>We use the term <dfn data-export>settings dictionary</dfn> for the set of
-              values that might be applied as settings to the object.</p>
+              values that might be applied as settings to the object. Do not
+              include inherent properties as members unless they are in the
+              <a>list of inherent constrainable track properties</a> (to avoid
+              a broken clock being right twice a day).</p>
```

2021-01-14 20:28 UTC, jan-ivar commented
I've created https://github.com/w3c/mediacapture-main/pull/766 as an alternative to this PR, since github wouldn't allow me to suggest changes outside lines already touched. PTAL

2021-01-21 02:29 UTC, jan-ivar commented
Closing in favor of https://github.com/w3c/mediacapture-main/pull/766

2021-01-21 02:29 UTC, closed without merging