Clarify that a source lifetime is bound to its context
w3c/mediacapture-main pull request #805
Opened 2021-07-09 09:09 UTC by youennf

Fixes https://github.com/w3c/mediacapture-main/issues/804
Change is consistent with existing browser behaviours which stop MediaStreamTracks when their context goes away.
We introduce a new slot shouldStopSource that will be used by mediacapture-extensions

2021-07-09 09:20 UTC, dontcallmedom reviewed
Suggestions to improve autolinking, using the newly set syntax for internal slots in ReSpec

2021-07-09 09:20 UTC, dontcallmedom commented on getusermedia.html
> +      <p>At creation of a {{MediaStreamTrack}} object, create an internal slot named <dfn>[[\shouldStopSource]]</dfn> on it,
```suggestion
      <p>At creation of a {{MediaStreamTrack}} object, create an internal slot named <dfn data-dfn-for="MediaStreamTrack" data-dfn-export="">[[\shouldStopSource]]</dfn> on it,
```

2021-07-09 09:20 UTC, dontcallmedom commented on getusermedia.html
> +              <li><p>If <var>track</track>.<a>[[\shouldStopSource]]</a> is <code>true</code>, <a href="#source-stopped">stop</a> <var>track</var>'s underlying source.</p></li>
```suggestion
              <li><p>If <var>track</track>.{{MediaStreamTrack/[[shouldStopSource]]}} is <code>true</code>, <a href="#source-stopped">stop</a> <var>track</var>'s underlying source.</p></li>
```

2021-07-09 09:20 UTC, dontcallmedom commented on getusermedia.html
> +          <p>Initialize <var>trackClone</var>.<a>[[\shouldStopSource]]</a> to
```suggestion
          <p>Initialize <var>trackClone</var>.{{MediaStreamTrack/[[shouldStopSource]]}} to
```

2021-07-09 09:20 UTC, dontcallmedom commented on getusermedia.html
> +          <var>track</var>.<a>[[\shouldStopSource]]</a>.</p>
```suggestion
          <var>track</var>.{{MediaStreamTrack/[[shouldStopSource]]}}.</p>
```

2021-07-09 09:20 UTC, dontcallmedom commented on getusermedia.html
> +            <dt><dfn id="navigator-mediaDevices">mediaDevices</dfn> of type {{MediaDevices}}, readonly</dt>
why changing the id?

2021-07-09 09:20 UTC, dontcallmedom commented on getusermedia.html
> +    Similarly, sources of a RTCPeerConnection object are bound
```suggestion
    Similarly, sources of a {{RTCPeerConnection}} object are bound
```

2021-07-09 09:20 UTC, dontcallmedom commented on getusermedia.html
> +    to the RTCPeerConnection itself, which is bound to its creation context.
```suggestion
    to the {{RTCPeerConnection}} itself, which is bound to its creation context.
```

2021-07-09 09:28 UTC, youennf commented on getusermedia.html
> +            <dt><dfn id="navigator-mediaDevices">mediaDevices</dfn> of type {{MediaDevices}}, readonly</dt>
mediaDevices felt too generic and error prone with MediaDevices.
I can change it though.

2021-07-09 09:29 UTC, youennf commented
> Suggestions to improve autolinking, using the newly set syntax for internal slots in ReSpec

Thanks, I should really take a ReSpec class!

2021-07-09 09:45 UTC, dontcallmedom commented on getusermedia.html
> +            <dt><dfn id="navigator-mediaDevices">mediaDevices</dfn> of type {{MediaDevices}}, readonly</dt>
the id that ReSpec automatically generates for that `dfn` is `dom-navigator-mediadevices`, so I think leaving it alone is probably best

2021-07-09 09:57 UTC, youennf commented on getusermedia.html
> +    by its <a href="#navigator-mediaDevices">navigator.mediaDevices</a> context.
```suggestion
    by its <a href="#dom-navigator-mediadevices">navigator.mediaDevices</a> context.
```

2021-07-09 09:58 UTC, youennf commented on getusermedia.html
> +            <dt><dfn id="navigator-mediaDevices">mediaDevices</dfn> of type {{MediaDevices}}, readonly</dt>
```suggestion
            <dt><dfn>mediaDevices</dfn> of type {{MediaDevices}}, readonly</dt>
```

2021-07-09 09:58 UTC, youennf commented on getusermedia.html
> +            <dt><dfn id="navigator-mediaDevices">mediaDevices</dfn> of type {{MediaDevices}}, readonly</dt>
OK, sounds good, I updated the PR accordingly, thanks for the feedback.

2021-07-09 11:11 UTC, dontcallmedom commented on getusermedia.html
> +    by its <a href="#dom-navigator-mediadevices">navigator.mediaDevices</a> context.
I had missed that link (which I now understand was your motivation for the new id.
```suggestion
    by its {{Navigator.mediaDevices}} context.
```
or ({{Navigator/mediaDevices | navigator.mediaDevices }} if the capitalization is an issue

2021-07-09 11:12 UTC, dontcallmedom commented on getusermedia.html
> +    a source is always <a href="#source-stopped">stopped</a> when its creation context goes away.
```suggestion
    a source is always [= source/stopped =] when its creation context goes away.
```

2021-07-09 11:12 UTC, dontcallmedom commented on getusermedia.html
> +          <p>Let <var>globalObject</var> be <var>context</var>'s <a data-cite="!HTML/#concept-relevant-global">relevant global object</a>.</p>
```suggestion
          <p>Let <var>globalObject</var> be <var>context</var>'s [=relevant global object=].</p>
```

2021-07-09 11:13 UTC, dontcallmedom commented on getusermedia.html
> +          <p>For each {{MediaStreamTrack}} object <var>track</var> whose <a data-cite="!HTML/#concept-relevant-global">relevant global object</a> is <var>globalObject</var>, run the following steps:
```suggestion
          <p>For each {{MediaStreamTrack}} object <var>track</var> whose [=relevant global object=] is <var>globalObject</var>, run the following steps:
```

2021-07-09 11:13 UTC, dontcallmedom commented on getusermedia.html
> +              <li><p>If <var>track</track>.{{MediaStreamTrack/[[shouldStopSource]]}} is <code>true</code>, <a href="#source-stopped">stop</a> <var>track</var>'s underlying source.</p></li>
```suggestion
              <li><p>If <var>track</track>.{{MediaStreamTrack/[[shouldStopSource]]}} is <code>true</code>, [= source/stopped | stop =] <var>track</var>'s underlying source.</p></li>
```

2021-07-09 11:27 UTC, youennf commented on getusermedia.html
> +    by its {{Navigator.mediaDevices}} context.
```suggestion
    by its {{Navigator.mediaDevices | navigator.mediaDevices}} context.
```

2021-07-09 11:31 UTC, youennf commented on getusermedia.html
> +    by its {{Navigator.mediaDevices | navigator.mediaDevices}} context.
```suggestion
    by its {{Navigator/mediaDevices | navigator.mediaDevices}} context.
```

2021-07-09 11:41 UTC, youennf commented on getusermedia.html
> +    by its {{Navigator/mediaDevices | navigator.mediaDevices}} context.
```suggestion
    by its navigator.{{mediaDevices}} context.
```

2021-08-09 15:14 UTC, alvestrand requested changes
I think this works without adding the new internal slot at all.

2021-08-09 15:14 UTC, alvestrand commented on getusermedia.html
> +      initialized to <code>true</code>. When a browsing context, <var>context</var>, goes away, the User Agent MUST run the following steps:
Link definition of "goes away", or use a more precise term.

2021-08-09 15:14 UTC, alvestrand commented on getusermedia.html
> +      <p>At creation of a {{MediaStreamTrack}} object, create an internal slot named <dfn data-dfn-for="MediaStreamTrack" data-dfn-export="">[[\shouldStopSource]]</dfn> on it,
This new flag inverts the normal procedure for stopping sources - it stops the source if one track has shouldStopSource=true rather than stopping the source when all tracks fed from it have stopped.

2021-08-09 15:14 UTC, alvestrand commented on getusermedia.html
> +              <li><p>If <var>track</track>.{{MediaStreamTrack/[[shouldStopSource]]}} is <code>true</code>, [= source/stopped | stop =] <var>track</var>'s underlying source.</p></li>
I think the shouldStopSource flag and all the logic should be deleted.

2021-08-09 15:14 UTC, alvestrand commented on getusermedia.html
> +        </li>
I think this should be deleted.

2021-08-09 15:14 UTC, alvestrand commented on getusermedia.html
> +    Except stated explicitly in the definition of specific sources,
Nit: Except stated explicitly -> Except if stated explicitly.

2021-08-09 15:14 UTC, alvestrand commented on getusermedia.html
> +    </p>
This section needs cleanup for English, but I think I agree with what it's trying to say.

2021-08-09 16:01 UTC, youennf commented
> I think this works without adding the new internal slot at all.

There are different ways to do this but I think we cannot do without a new slot, for instance a slot that stores in each context the list of its active sources.
Then when context goes away, iterate through them to stop them.
That might be more straightforward, I'll have a try. In any case, this should be functionally equivalent to this PR.

2021-08-10 11:50 UTC, youennf commented
@alvestrand, I updated the PR with the alternative I mentioned above, hopefully this will be much clearer.
PTAL.

2021-08-10 11:50 UTC, youennf commented on getusermedia.html
> +              <li><p>If <var>track</track>.{{MediaStreamTrack/[[shouldStopSource]]}} is <code>true</code>, [= source/stopped | stop =] <var>track</var>'s underlying source.</p></li>
Updated PR with new approach

2021-08-10 11:50 UTC, youennf commented on getusermedia.html
> +      <p>At creation of a {{MediaStreamTrack}} object, create an internal slot named <dfn data-dfn-for="MediaStreamTrack" data-dfn-export="">[[\shouldStopSource]]</dfn> on it,
Updated PR with new approach

2021-08-10 11:50 UTC, youennf commented on getusermedia.html
> +      initialized to <code>true</code>. When a browsing context, <var>context</var>, goes away, the User Agent MUST run the following steps:
Done

2021-08-10 11:51 UTC, youennf commented on getusermedia.html
> +    </p>
Can you do some suggestions?

2021-08-10 15:14 UTC, dontcallmedom commented on getusermedia.html
> +    Stopping one of the source is independent of stopping the other one.
```suggestion
    One source can be stopped independently of the other one.
```

2021-08-12 14:01 UTC, alvestrand requested changes
Not quite there yet - "initialize the underlying source" is only called from "clone()", which is perhaps the one place where it currently shouldn't be called when creating a track.

2021-08-12 14:01 UTC, alvestrand commented on getusermedia.html
> +    Similarly, sources of a {{RTCPeerConnection}} object are bound
I'm not sure what "sources of a RTCPeerConnection" means. The RTCRtpReceiver is the source of the track; the lifetime of the source should be the lifetime of the RTCRtpReceiver.

2021-08-12 14:10 UTC, youennf commented on getusermedia.html
> +          <p>[=Initialize the underlying source=] of <var>trackClone</var> to the source of <var>track</var>.</p>
Oh right, there was no such issue with the previous approach of having a boolean flag in MediaStreamTrack.
We should then update it to not use this algorithm here and say why explicitly.

2021-08-12 14:25 UTC, youennf commented on getusermedia.html
> +        <li><p>If <var>tieSourceToContext</var> is set to <code>false</code>, abort these steps.</p></li>
Updated to put the mandatory step first

2021-08-12 15:18 UTC, youennf commented
@alvestrand, PTAL.
I think all your comments are now addressed. I also rebased to main which makes the PR smaller.

2021-08-19 14:00 UTC, alvestrand reviewed
Stopping tracks with out-of-process sourcs still seems odd to me.

2021-08-19 14:00 UTC, alvestrand commented on getusermedia.html
> +        set <var>track</var>.{{MediaStreamTrack/readyState}} to {{MediaStreamTrackState/"ended"}}.</p></li>
This stops tracks whose source is not in this context. I think this step is not needed; all tracks whose source is in this context will be stopped in the next step.

2021-08-19 14:00 UTC, alvestrand commented on getusermedia.html
> +        <li><p>If <var>tieSourceToContext</var> is set to <code>false</code>, abort these steps.</p></li>
But the step that comes before the "if" does nothing; "source" is an algorithm-local variable.

The alternative is to rename this algorithm to "RegisterSource" (or something like that) and replace the call to "initalize" in clone() by a "Note that this does not call RegisterSource".

But it's relatively harmless, just confusing, so I'm willing to live with thils.

2021-08-19 14:00 UTC, alvestrand commented on getusermedia.html
> +    </p>
On today's read, I'm OK with it.

2021-08-19 14:15 UTC, alvestrand approved these changes
After discussion, I think this is Good Enough.

2021-08-19 14:17 UTC, merged